//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace RentalsMoviesMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
       [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }
        [Display(Name = "Membership Name")]
        public byte MembershipTypeId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool IsSubscribedToNewsletter { get; set; }
    
        public virtual MembershipTypes MembershipTypes { get; set; }
    }
}
