//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalsMoviesMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }

        public byte GenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<byte> NumberInStock { get; set; }
        public Nullable<byte> NumberAvailable { get; set; }
        public string Name { get; set; }
        
        public  Genres Genres { get; set; }
      
       }

    }


